version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TU_CONTRASEÑA
      MYSQL_DATABASE: Database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: